[en]
title = "GetCourageNow.org - It's A Numbers Game"
contentDir = "content/en"
languageName ="English"
languageCode= "en-us"
#if colon ":" must be prefixed with a space : "&nbsp;" (example in [fr])
beforeColon= ""
# Weight used for sorting. (alphabetical order using languageCode, with English first)
weight = 10
description = """
  GetCourageNow is a free, mobile friendly, open source, volunteer recruitment app that aims to help climate justice campaigns to organise and commit strikers on a mass scale. 
"""


